import * as React from 'react';

interface Props {
  text?: string;
  setText: (text: string) => void
}

const sampleText = 'This is an example note.\n'
    + '\n'
    + '# H1\n'
    + '## H2\n'
    + '### H3\n'
    + '#### H4\n'
    + '##### H5\n'
    + '###### H6\n'
    + '\n'
    + '## Emphasis\n'
    + '\n'
    + 'Emphasis aka italic: `*asterisks* or _underscores_` *asterisks* or _underscores_\n'
    + '\n'
    + 'Strong: `**asterisks** or __underscores__` **asterisks** or __underscores__\n'
    + '\n'
    + 'Emphasis  an strong: `**asterisks and _underscores_**` **asterisks and _underscores_**\n'
    + '\n'
    + 'Strikethrough: `~~Scratch this.~~` ~~Scratch this.~~\n'
    + '\n'
    + 'Highlight: `==highlight==`  ==highlight==\n'
    + '\n'
    + '## Lists\n'
    + '\n'
    + '1. First ordered list item\n'
    + '2. Another item\n'
    + '   * Unordered sub-list.\n'
    + "1. Actual numbers don't matter, just that it's a number\n"
    + '   1. Ordered sub-list\n'
    + '4. And another item.\n'
    + '\n'
    + "   You can have properly indented paragraphs within list items. Notice the blank line above, and the leading spaces (at least one, but we'll use three here to also align the raw Markdown).\n"
    + '\n'
    + '   To have a line break without a paragraph, you will need to use two trailing spaces.  \n'
    + '   Note that this line is separate, but within the same paragraph.  \n'
    + '   (This is contrary to the typical GFM line break behaviour, where trailing spaces are not required.)\n'
    + '\n'
    + '\n'
    + '* Unordered list can use asterisks\n'
    + '- Or minuses\n'
    + '+ Or pluses\n'
    + '\n'
    + '## Links\n'
    + '\n'
    + "[I'm an inline-style link](https://www.google.com)\n"
    + '\n'
    + "[I'm an inline-style link with title](https://www.google.com \"Google's Homepage\")\n"
    + '\n'
    + "[I'm a reference-style link][Arbitrary case-insensitive reference text]\n"
    + '\n'
    + '[You can use numbers for reference-style link definitions][1]\n'
    + '\n'
    + 'Or leave it empty and use the [link text itself].\n'
    + '\n'
    + 'URLs and URLs in angle brackets will automatically get turned into links. \n'
    + 'http://www.example.com or <http://www.example.com> and sometimes \n'
    + 'example.com (but not on Github, for example).\n'
    + '\n'
    + 'Some text to show that the reference links can follow later.\n'
    + '\n'
    + '[arbitrary case-insensitive reference text]: https://www.mozilla.org\n'
    + '[1]: http://slashdot.org\n'
    + '[link text itself]: http://www.reddit.com\n'
    + '\n'
    + '## Images\n'
    + '\n'
    + "Here's our logo (hover to see the title text):\n"
    + '\n'
    + 'Inline-style: \n'
    + '![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")\n'
    + '\n'
    + 'Reference-style: \n'
    + '![alt text][logo]\n'
    + '\n'
    + '[logo]: https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 2"\n'
    + '\n'
    + '\n'
    + '## Code and Syntax Highlighting\n'
    + '\n'
    + 'Inline `code` has `back-ticks around` it.\n'
    + '\n'
    + '```javascript\n'
    + 'var s = "JavaScript syntax highlighting";\n'
    + 'alert(s);\n'
    + '```\n'
    + ' \n'
    + '```python\n'
    + 's = "Python syntax highlighting"\n'
    + 'print s\n'
    + '```\n'
    + ' \n'
    + '```\n'
    + 'No language indicated, so no syntax highlighting. \n'
    + '```\n'
    + '\n'
    + '## Tables\n'
    + '\n'
    + 'Colons can be used to align columns.\n'
    + '\n'
    + '| Tables        | Are           | Cool  |\n'
    + '| ------------- |:-------------:| -----:|\n'
    + '| col 3 is      | right-aligned | $1600 |\n'
    + '| col 2 is      | centered      |   $12 |\n'
    + '| zebra stripes | are neat      |    $1 |\n'
    + '| This is a table | For real | Yess  |\n'
    + '\n'
    + 'There must be at least 3 dashes separating each header cell.\n'
    + "The outer pipes (|) are optional, and you don't need to make the \n"
    + 'raw Markdown line up prettily. You can also use inline Markdown.\n'
    + '\n'
    + 'Markdown | Less | Pretty\n'
    + '--- | --- | ---\n'
    + '*Still* | `renders` | **nicely**\n'
    + '==hello== | 2 | 3\n'
    + '\n'
    + '## Blockquotes\n'
    + '\n'
    + '> Blockquotes are very handy in email to emulate reply text.\n'
    + '> This line is part of the same quote.\n'
    + '\n'
    + 'Quote break.\n'
    + '\n'
    + "> This is a very long line that will still be quoted properly when it wraps. Oh boy let's keep writing to make sure this is long enough to actually wrap for everyone. Oh, you can *put* **Markdown** into a blockquote. \n"
    + '\n'
    + '## Horizontal Rule\n'
    + '\n'
    + 'Three or more...\n'
    + '\n'
    + '---\n'
    + '\n'
    + 'Hyphens\n'
    + '\n'
    + '***\n'
    + '\n'
    + 'Asterisks\n'
    + '\n'
    + '___\n'
    + '\n'
    + 'Underscores\n'
    + '\n'
    + '## Line Breaks\n'
    + '\n'
    + "Here's a line for us to start with.\n"
    + '\n'
    + 'This line and other lines under it\n'
    + 'only separated by one new line character\n'
    + 'so it still a one line.\n'
    + '\n'
    + 'This line is separated from the one above by two newlines, so it will be a *separate paragraph*.\n'
    + '\n'
    + '## Emoji\n'
    + '\n'
    + "You can insert emoji using unicode or it's github shortname.\n"
    + 'For example, `:tent:` will make a :tent:, while `:U+1F44B:` will make :U+1F44B:.\n'
    + '\n'
    + 'You can find list of shortname [here](https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md#flags)\n'
    + 'and list of unicode names [from this link](https://unicode.org/emoji/charts/full-emoji-list.html).\n'
    + '\n'
    + '## Commands\n'
    + '\n'
    + "Commands can be inserted insert a 'double colon' pair, i.e `::command_name::`.\n"
    + '\n'
    + 'Commands can have optional options, inserted after command name and separated by a colon\n'
    + 'and separated from each other by a pipe. i.e `::command_name:op_1|op_2::\n'
    + '\n'
    + 'Currently supported commands:\n'
    + '\n'
    + '### Table Of Content\n'
    + '\n'
    + 'Use `::table_of_content::`.\n'
    + '\n'
    + 'Content of the table will be all heading tag\n'
    + '\n'
    + '**Options**:\n'
    + '\n'
    + 'This command comes with greate some styling options for the table\n'
    + 'or each heading level\n'
    + '\n'
    + 'Options have 2 parts: `scope` and `modifier`.\n'
    + 'Combine a scope then a `_` and a modifier.\n'
    + '\n'
    + 'Example: `toc_underline`, `h3_exclude`.\n'
    + '\n'
    + '\n'
    + '#### Scope name\n'
    + '\n'
    + '| Tag nane | Explains |\n'
    + '| --- | --- |\n'
    + '| toc | The whole table of content |\n'
    + '| h1 | `# first level` |\n'
    + '| h2 | `## second level` |\n'
    + '| h3 | `### third level` |\n'
    + '| h4 | `#### fouth level` |\n'
    + '| h5 | `##### fifth level` |\n'
    + '| h6 | `####### six level` | \n'
    + '\n'
    + '#### Line modifiers\n'
    + '\n'
    + '**Scope**: `toc`, `h{n}`.\n'
    + '\n'
    + '| Modifiers name | Render |\n'
    + '| -------------- | ------ |\n'
    + '| none           | <span style="text-decoration-line: none">heading</style>         |\n'
    + '| underline      | <span style="text-decoration-line: underline">heading</style>    |\n'
    + '| overine        | <span style="text-decoration-line: overline">heading</style>     |\n'
    + '| line-through   | <span style="text-decoration-line: line-through">heading</style> |\n'
    + '\n'
    + '#### Line style modifiers\n'
    + '\n'
    + '**Scope**: `toc`, `h{n}`.\n'
    + '\n'
    + 'Must have a line modifier for this to have effect.\n'
    + '\n'
    + '| Modifiers name | Render |\n'
    + '| -------------- | ------ |\n'
    + '| solid          | <span style="text-decoration-line: underline; text-decoration-style: solid">heading</style>  |\n'
    + '| double         | <span style="text-decoration-line: underline; text-decoration-style: double">heading</style> |\n'
    + '| dashe          | <span style="text-decoration-line: underline; text-decoration-style: dotted">heading</style> |\n'
    + '| dotted         | <span style="text-decoration-line: underline; text-decoration-style: dashed">heading</style> |\n'
    + '| wavy           | <span style="text-decoration-line: underline; text-decoration-style: wavy">heading</style>   |\n'
    + '\n'
    + '#### Font style modifier\n'
    + '\n'
    + '**Scope**: `toc`, `h{n}`\n'
    + '\n'
    + '| Modifiers name | Render |\n'
    + '| -------------- | ------ |\n'
    + '| normal         | <span style="font-style: normal">heading</style>  |\n'
    + '| italic         | <span style="font-style: italic">heading</style>  |\n'
    + '| oblique        | <span style="font-style: oblique">heading</style> |\n'
    + '\n'
    + '#### Font weight modifier\n'
    + '\n'
    + '**Scope**: `toc`, `h{n}`\n'
    + '\n'
    + '| Modifiers name | Render |\n'
    + '| -------------- | ------ |\n'
    + '| thin           | <span style="font-weight: 100">heading</style> |\n'
    + '| extralight     | <span style="font-weight: 200">heading</style> |\n'
    + '| light          | <span style="font-weight: 300">heading</style> |\n'
    + '| ordinary       | <span style="font-weight: 400">heading</style> |\n'
    + '| medium         | <span style="font-weight: 500">heading</style> |\n'
    + '| semibold       | <span style="font-weight: 600">heading</style> |\n'
    + '| bold           | <span style="font-weight: 700">heading</style> |\n'
    + '| extrabold      | <span style="font-weight: 800">heading</style> |\n'
    + '| back           | <span style="font-weight: 900">heading</style> |\n'
    + '\n'
    + '#### Color modifier\n'
    + '\n'
    + '**Scope**: `toc`, `h{n}`\n'
    + '\n'
    + '**Name**: `color_{color_name|color_hash_code}`\n'
    + '\n'
    + '`color_name` is a valid _css_ color name.\n'
    + 'Ex: `color_red`, `colode_aquamarine`\n'
    + '\n'
    + '`color_hash_code` is a vaidl _css_ color hash code.\n'
    + 'Ex: `color_#ff0000`, `color_#00FBDECE`.\n'
    + '\n'
    + 'Change color of `scope`.\n'
    + '\n'
    + '#### Exclude modifier\n'
    + '\n'
    + '**Scope**: `h{n}`\n'
    + '\n'
    + '**Name**: `exclude`\n'
    + '\n'
    + 'Remove headings from table of content.\n'
    + '\n'
    + '#### Indent modifier\n'
    + '\n'
    + '**Scope**: `toc`\n'
    + '\n'
    + '**Name**: `indent_{n}`\n'
    + '\n'
    + 'Indent table of content.\n'
    + '\n'
    + '`n` can be a negative to indent backwards.\n'
    + '\n'
    + '#### No link modifier\n'
    + '\n'
    + '**Scope**: `toc`\n'
    + '\n'
    + '**Name**: `no_link`\n'
    + '\n'
    + 'Make table of content text only.\n'
    + '\n'
    + 'Examples:\n'
    + '\n'
    + 'Normal table of content:\n'
    + '\n'
    + '::table_of_content::\n'
    + '\n'
    + 'With options:\n'
    + '\n'
    + '::table_of_content:toc_indent_2|toc_no_link|h1_underline|h2_line-through|h2_color_red|h2_medium|h3_exclude|h4_extrabold|h4_color_blue|h4_overline|h4_wavy|h5_thin::\n'
    + '\n'
    + '## HTML tags\n'
    + '\n'
    + 'HTML tags are **not sanitized** (this is intentional). Use set can put any tag they want. For example:\n'
    + '\n'
    + '`<strong>strong</strong>` will create <strong>strong</strong> and have the same effect as **strong**.\n'
    + '\n'
    + '`<input></input>` will create <input></input>\n'
    + '\n'
    + '```html\n'
    + "<button onclick=\"alert('hello')\" style=\"border: black solid 2px;\">click me</button>\n"
    + '```\n'
    + "will create <button onclick=\"alert('hello')\" style=\"border: black solid 2px\">click me</button> \n"
    + '\n'
    + '\n'
    + '```html\n'
    + '<button\n'
    + "    onclick=\"alert('hello')\"\n"
    + '    style="border: black solid 2px; border-radius: 5px; padding: 3px 2px"\n'
    + '>\n'
    + '    click me\n'
    + '</button>\n'
    + '```\n'
    + 'will create\n'
    + "<button onclick=\"alert('hello')\" style=\"border: black solid 2px; border-radius: 5px; padding: 3px 2px\">click me</button>\n"
    + '\n'
    + '**Use this at you own risk.**\n';

export default function TextEditor({ setText }: Props) {
  setText(sampleText);

  return (
    <div>{sampleText}</div>
  );
}
